{
  'circle_up_nonlocal': {
    'optimizer': 'hillclimber',
    'num_trials': 1,
    'target_population_size': 500,
    'max_generations': 4000,
    'n_random_individuals_per_generation': 100,
    'mutate_layers': None,
    'neighbor_map_type': 'random',
    'sim_steps': 100,
    'shape': 'circle',
    'layers': [
        {'res': 1},
        {'res': 2},
        {'res': 4},
        {'res': 8, 'base': True}
    ],
    'activation': 'sigmoid'
  },
}
